# UseVivado
#
# This package assumes that find_package(Vivado) has been called,
# so that the XILINX_VIVADO program has been found.
#
# The basic approach is to use Vivado to create the block design, which is then
# exported (File..Export Block Design) as a TCL file, specified by the EXPORTED_TCL
# parameter. In that case, it is only necessary to put the TCL file under source
# code control, since the Vivado project is regenerated by running the TCL file.
#
# The vivado_block_build function creates a top-level TCL file, called
# make-${PROJ_NAME}.tcl, that calls ${EXPORTED_TCL}, creates the top-level Verilog
# wrapper, and generates the output files, including the final ${HW_FILE} used by Vitis.
#
# The easiest way to make changes to the block design is to open the project file
# ${PROJ_NAME}.xpr in the build directory, make the changes, and then export the
# TCL file again. This file can then be manually copied to the source directory
# to update ${EXPORTED_TCL} in the repository.
#
# Function: vivado_block_build
#
# Parameters:
#   - PROJ_NAME:         project name
#   - BD_NAME:           board name
#   - FPGA_PARTNUM:      FPGA part number
#   - EXPORTED_TCL       Input TCL file (exported from Vivado)
#   - HW_FILE            Output hardware file (XSA)
#

function (vivado_block_build ...)

  # set all keywords and their values to ""
  set (FUNCTION_KEYWORDS
       PROJ_NAME
       BD_NAME
       FPGA_PARTNUM
       EXPORTED_TCL
       HW_FILE)

  # reset local variables
  foreach(keyword ${FUNCTION_KEYWORDS})
    set (${keyword} "")
  endforeach(keyword)

  # parse input
  foreach (arg ${ARGV})
    list (FIND FUNCTION_KEYWORDS ${arg} ARGUMENT_IS_A_KEYWORD)
    if (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (CURRENT_PARAMETER ${arg})
      set (${CURRENT_PARAMETER} "")
    else (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
      set (${CURRENT_PARAMETER} ${${CURRENT_PARAMETER}} ${arg})
    endif (${ARGUMENT_IS_A_KEYWORD} GREATER -1)
  endforeach (arg)

  if (PROJ_NAME AND BD_NAME AND FPGA_PARTNUM AND EXPORTED_TCL AND HW_FILE)

    file(TO_NATIVE_PATH ${XILINX_VIVADO} VIVADO_NATIVE)

    # Create TCL file
    set (TCL_FILE "${CMAKE_CURRENT_BINARY_DIR}/make-${PROJ_NAME}.tcl")
    file (WRITE  ${TCL_FILE} "create_project -force -part ${FPGA_PARTNUM} ${PROJ_NAME} ${CMAKE_CURRENT_BINARY_DIR}\n")
    file (APPEND ${TCL_FILE} "create_bd_design ${BD_NAME}\n")
    file (APPEND ${TCL_FILE} "source ${EXPORTED_TCL}\n")
    file (APPEND ${TCL_FILE} "make_wrapper -top -files [get_files ${BD_NAME}.bd]\n")
    file (APPEND ${TCL_FILE} "add_files ${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME}.gen/sources_1/bd/${BD_NAME}/hdl/${BD_NAME}_wrapper.v\n")
    file (APPEND ${TCL_FILE} "generate_target all [get_files ${BD_NAME}.bd]\n")
    # Could add -minimal below
    file (APPEND ${TCL_FILE} "write_hw_platform -fixed -force -file ${HW_FILE}\n")

    add_custom_command (OUTPUT ${HW_FILE}
                        COMMAND ${VIVADO_NATIVE} -mode batch -source ${TCL_FILE}
                        DEPENDS ${EXPORTED_TCL})

    add_custom_target(${PROJ_NAME} ALL
                      DEPENDS ${HW_FILE})

  else ()

    message (SEND_ERROR "vivado_block_build: required parameter missing")

  endif ()

endfunction (vivado_block_build)
